In [29]:
import os
import scipy.io
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MultiLabelBinarizer 
def si(k):
    s = k.split(".")
    return int(s[0])

In [30]:
pdir = os.getcwd()

In [31]:
pdir

'/mnt/c/Users/indum/Desktop/fyp_code/lstm 3 words'

In [32]:
file = "data"

In [33]:
cwd = pdir+"/"+file 

In [34]:
cwd

'/mnt/c/Users/indum/Desktop/fyp_code/lstm 3 words/data'

In [35]:
l1 = os.listdir(cwd)
X = []
Y = []
print(l1)

['backward', 'come', 'down', 'help', 'left', 'light', 'medicine', 'no', 'pain', 'right', 'spoon', 'stop', 'telephone', 'television', 'toilet', 'upward', 'water', 'yes']


In [36]:
for i in l1:
    tmp1 = os.path.join(cwd,i)
    l2 = os.listdir(tmp1)
    print(l2)
    for j in l2:
        tmp2 = os.path.join(tmp1,j)
        l3 = os.listdir(tmp2)
        l3.sort(key=si)
        tmp_x = []
        tmp_y = -1
        for file in l3:
            if file.endswith(".mat"):
                data = scipy.io.loadmat(os.path.join(tmp2,file))
                s = data['sequence_data']
                Y.append(data['y'][0])
                X.append(s)
                    
            
                    
            

['Ameya', 'Mitesh', 'Mukund', 'Naga', 'Rohit', 'Udit']
['Ameya', 'Mitesh', 'Mukund', 'Naga', 'Rohit', 'Udit']
['Ameya', 'Mitesh', 'Mukund', 'Naga', 'Rohit', 'Udit']
['Ameya', 'Mitesh', 'Mukund', 'Naga', 'Rohit', 'Udit']
['Ameya', 'Mitesh', 'Mukund', 'Naga', 'Rohit', 'Udit']
['Ameya', 'Mitesh', 'Mukund', 'Naga', 'Rohit', 'Udit']
['Ameya', 'Mitesh', 'Mukund', 'Naga', 'Rohit', 'Udit']
['Ameya', 'Mitesh', 'Mukund', 'Naga', 'Rohit', 'Udit']
['Ameya', 'Mitesh', 'Mukund', 'Naga', 'Rohit', 'Udit']
['Ameya', 'Mitesh', 'Mukund', 'Naga', 'Rohit', 'Udit']
['Ameya', 'Mitesh', 'Mukund', 'Naga', 'Rohit', 'Udit']
['Ameya', 'Mitesh', 'Mukund', 'Naga', 'Rohit', 'Udit']
['Ameya', 'Mitesh', 'Mukund', 'Naga', 'Rohit', 'Udit']
['Ameya', 'Mitesh', 'Mukund', 'Naga', 'Rohit', 'Udit']
['Ameya', 'Mitesh', 'Mukund', 'Naga', 'Rohit', 'Udit']
['Ameya', 'Mitesh', 'Mukund', 'Naga', 'Rohit', 'Udit']
['Ameya', 'Mitesh', 'Mukund', 'Naga', 'Rohit', 'Udit']
['Ameya', 'Mitesh', 'Mukund', 'Naga', 'Rohit', 'Udit']


In [37]:
d = {}
for i in X:
    if i.shape in d:
        d[i.shape] += 1
    else:
        d[i.shape] = 1
    

In [38]:
d

{(1280, 19): 1278}

In [39]:
x_tmp = []
y_tmp = []
for i in range(len(X)):
    if Y[i] in [5,11,12]:
        x_tmp.append(X[i])
        if Y[i] == 5:
            y_tmp.append(Y[i] - 5)
        # if Y[i] == 3:
        #     y_tmp.append(Y[i] - 2)
        # if Y[i] == 4:
        #     y_tmp.append(Y[i] - 2)
        # if Y[i] == 5:
        #     y_tmp.append(Y[i] - 3)
        # if Y[i] == 7:
        #     y_tmp.append(Y[i] - 4)
        # if Y[i] == 9:
        #     y_tmp.append(Y[i] - 5)
        if Y[i] == 12:
            y_tmp.append(Y[i] - 10)
        if Y[i] == 11:
            y_tmp.append(Y[i] - 10)
        # if Y[i] == 13:
        #     y_tmp.append(Y[i] - 7)
        # if Y[i] == 15:
        #     y_tmp.append(Y[i] - 8)
            
            
            
            
        

In [40]:
X = np.array(x_tmp)

In [41]:
X.shape

(213, 1280, 19)

In [42]:
Y = np.array(y_tmp)

In [43]:
shape_y = Y.shape

In [44]:
shape_y

(213, 1)

In [45]:
# X = np.array(X)
# Y = np.array(Y)

In [46]:
np.save("X_data",X)

In [47]:
np.save("Y_data",Y)

In [48]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.1, random_state=140, stratify=Y)

In [49]:
np.save("EEG_X_train",X_train)
np.save("EEG_X_test",X_test)
np.save("EEG_y_train",y_train)
np.save("EEG_y_test",y_test)

In [50]:
X_train.shape

(191, 1280, 19)

In [51]:
X_test.shape

(22, 1280, 19)

In [52]:
y_train.shape

(191, 1)

In [53]:
y_test.shape

(22, 1)

In [54]:
y_test[0]

array([1], dtype=uint8)

In [55]:
X[1:2,:]

array([[[-3.71666764e-01, -3.76794907e-01, -4.08675889e-01, ...,
         -4.16275426e-01, -3.96442489e-01, -4.39753668e-01],
        [-1.48143048e+00, -1.50143404e+00, -1.62829693e+00, ...,
         -1.65821098e+00, -1.58096692e+00, -1.75245328e+00],
        [-1.80675053e+00, -1.83012010e+00, -1.98379703e+00, ...,
         -2.02009618e+00, -1.93109193e+00, -2.13591320e+00],
        ...,
        [-4.49571287e-03, -3.28273026e-03,  1.65287051e-03, ...,
          1.59818724e-02, -5.34283409e-07,  2.04934771e-05],
        [-3.52106345e-03,  2.44861507e-03,  8.43080750e-03, ...,
          2.98115598e-02,  7.20037750e-03,  4.56648185e-05],
        [ 6.37030020e-04,  7.18117965e-03,  9.91783868e-03, ...,
          3.24791809e-02,  1.02321412e-02, -7.12589472e-05]]])

In [56]:
print(y_test)

[[1]
 [0]
 [0]
 [0]
 [1]
 [2]
 [0]
 [0]
 [1]
 [2]
 [0]
 [1]
 [0]
 [2]
 [2]
 [1]
 [2]
 [1]
 [0]
 [1]
 [2]
 [2]]
